package com.bankeen.data.error.apiv2;

import android.support.annotation.Keep;

@Keep
public enum ApiErrorType {
    PARAM_REQUIRED,
    INVALID_REQUEST,
    MISSING_VERSION_HEADER,
    INVALID_VERSION_HEADER,
    MISSING_DEVICE_HEADER,
    INVALID_DEVICE_HEADER,
    VALIDATION_ERROR,
    AUTHENTICATION_ERROR,
    MISSING_AUTHORIZATION_HEADER,
    INVALID_AUTHORIZATION_HEADER,
    MISSING_ACCESS_TOKEN_PARAMETER,
    INVALID_ACCESS_TOKEN_PARAMETER,
    INVALID_TOKEN,
    EXPIRED_TOKEN,
    MISSING_CLIENT_ID,
    MISSING_CLIENT_SECRET,
    INVALID_CLIENT_CREDENTIALS,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_SERVER_ERROR
}